// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcQHJ9n7h789zNxyrV2ThkghzozRbP13I',
    appId: '1:769723259158:web:1526ae3319ba4f1b5b9837',
    messagingSenderId: '769723259158',
    projectId: 'proxieberlin7',
    authDomain: 'proxieberlin7.firebaseapp.com',
    storageBucket: 'proxieberlin7.appspot.com',
    measurementId: 'G-KTMZQF1GSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXATCRNi8vuFmnlNAeOvkW73e8S9ExdE',
    appId: '1:769723259158:android:f7f14069ba3ea5565b9837',
    messagingSenderId: '769723259158',
    projectId: 'proxieberlin7',
    storageBucket: 'proxieberlin7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANiH_WqsAwOxFcOINNfVx_6mgLlv1p6Mc',
    appId: '1:769723259158:ios:5f21300fd8348dae5b9837',
    messagingSenderId: '769723259158',
    projectId: 'proxieberlin7',
    storageBucket: 'proxieberlin7.appspot.com',
    iosClientId: '769723259158-3ngt10q7caa3qglsgm4d7nrirhmd4q8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANiH_WqsAwOxFcOINNfVx_6mgLlv1p6Mc',
    appId: '1:769723259158:ios:8098ed72e616a95b5b9837',
    messagingSenderId: '769723259158',
    projectId: 'proxieberlin7',
    storageBucket: 'proxieberlin7.appspot.com',
    iosClientId: '769723259158-m7mth1qkpqbp1uhtnvasrb94tdujubvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectx.RunnerTests',
  );
}
